### ISSUE TITLE
Errow with latest CoFH mods

### ISSUE THREAD

**Issue by Xen1290** [RS485/LogisticsPipes#592] opened 2015-02-22 17:07 UTC
With latest version of CoFH mods out today, there is a problem with LogisticPipes, here is the log
http://pastebin.com/cW8Dr8iK

**Comment by davboecki** [comment] 2015-02-22 18:26
What Forge version are you using? Please update to the lastest forge build (1291)
Duplicate of: https://github.com/RS485/LogisticsPipes/issues/584.

**Closed as completed by davboecki** 2015-02-22 18:26 UTC
Labels: Duplicate

**Comment by Xen1290** [comment] 2015-02-22 18:52
Forge 1291 @davboecki
