### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Patus** [RS485/LogisticsPipes#369] opened 2014-06-06 14:02 UTC
If connect three Logistics IC2  power providers game crash. I'm using build 229.

Description: Ticking tile entity

java.lang.StackOverflowError
    at java.util.Collections$UnmodifiableCollection$1.<init>(Collections.java:1064)
    at java.util.Collections$UnmodifiableCollection.iterator(Collections.java:1063)
    at logisticspipes.routing.ServerRouter.getRoutersOnSide(ServerRouter.java:1145)
    at logisticspipes.blocks.powertile.LogisticsPowerProviderTileEntity.sendPowerLaserPackets(LogisticsPowerProviderTileEntity.java:138)
    at logisticspipes.blocks.powertile.LogisticsPowerProviderTileEntity.sendPowerLaserPackets(LogisticsPowerProviderTileEntity.java:155)
    at logisticspipes.blocks.powertile.LogisticsPowerProviderTileEntity.sendPowerLaserPackets(LogisticsPowerProviderTileEntity.java:155)
    at logisticspipes.blocks.powertile.LogisticsPowerProviderTileEntity.sendPowerLaserPackets(LogisticsPowerProviderTileEntity.java:155)
    at logisticspipes.blocks.powertile.LogisticsPowerProviderTileEntity.sendPowerLaserPackets(LogisticsPowerProviderTileEntity.java:155)
...

**Comment by davboecki** [comment] 2014-06-09 13:06
could you please post a screenshot of your setup and a full crash log.

**Comment by Patus** [comment] 2014-06-09 16:30
https://www.dropbox.com/s/7spdyhldp5oxun8/2014-06-09_18.09.03.png
https://www.dropbox.com/s/ry70qmezo4oo2p1/2014-06-09_18.10.31.png
https://www.dropbox.com/s/wqsj7sg07ybd9ef/2014-06-09_18.13.54.png

and crash report
https://www.dropbox.com/s/7iynzlzf9hcfi1g/crash-2014-06-09_15.40.45-server.txt

**Comment by AartBluestoke** [comment] 2014-06-09 23:21
https://www.dropbox.com/s/ry70qmezo4oo2p1/2014-06-09_18.10.31.png
@davboecki can we handle power not going in straight lines, in non LP pipes?

**Comment by AartBluestoke** [comment] 2014-06-09 23:22
also i have no idea if phase pipes teleport power

**Comment by davboecki** [comment] 2014-06-10 08:29
Both is a No. Power can only flow from LP to LP in straigt lines and not trough teleport pipes. But that still shouldn't cause a crash. Maybe it's related to the teleport pipes but we will see.

**Comment by Patus** [comment] 2014-06-10 14:11
Power going to down about 160 block and every floor has LP pipes. From every power provider the power lasers go to LP to LP straight to suppliers. No teleport pipes is used to transfer the power laser.

**Comment by davboecki** [comment] 2014-07-03 00:04
Could you retest this with the newest build and post a new crashreport if it happend again.

**Comment by Patus** [comment] 2014-07-04 17:43
That is possibly same error. Now it doesn't crash  but freezes.

2014-07-02 17:58:48 [INFO] [STDERR] java.lang.Throwable
2014-07-02 17:58:48 [INFO] [STDERR] at logisticspipes.pipes.basic.CoreRoutedPipe.getRouter(CoreRoutedPipe.java:867)
2014-07-02 17:58:48 [INFO] [STDERR] at logisticspipes.blocks.powertile.LogisticsPowerProviderTileEntity.func_70316_g(LogisticsPowerProviderTileEntity.java:101)
2014-07-02 17:58:48 [INFO] [STDERR] at logisticspipes.blocks.powertile.LogisticsIC2PowerProviderTileEntity.func_70316_g(LogisticsIC2PowerProviderTileEntity.java:30)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.world.World.func_72939_s(World.java:2209)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-07-02 17:58:48 [INFO] [STDOUT] Hey, don't get routers for pipes that aren't ready
2014-07-02 17:58:48 [INFO] [STDERR] java.lang.Throwable
2014-07-02 17:58:48 [INFO] [STDERR] at logisticspipes.pipes.basic.CoreRoutedPipe.getRouter(CoreRoutedPipe.java:867)
2014-07-02 17:58:48 [INFO] [STDERR] at logisticspipes.blocks.powertile.LogisticsPowerProviderTileEntity.func_70316_g(LogisticsPowerProviderTileEntity.java:101)
2014-07-02 17:58:48 [INFO] [STDERR] at logisticspipes.blocks.powertile.LogisticsIC2PowerProviderTileEntity.func_70316_g(LogisticsIC2PowerProviderTileEntity.java:30)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.world.World.func_72939_s(World.java:2209)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:550)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:668)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-07-02 17:58:48 [INFO] [STDERR] at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-07-02 17:58:49 [WARNING] [IC2] EnergyNet.addTileEntity: atomicscience.process.turbine.TileElectricTurbine@72124bbb (atomicscience.process.turbine.TileElectricTurbine@72124bbb) is conflicting with atomicscience.process.turbine.TileElectricTurbine@7a89af38 using the same position (already added, prev. te not removed, overlapping), aborting
2014-07-02 17:58:49 [WARNING] [IC2] EnergyNet.addTileEntity: atomicscience.process.turbine.TileElectricTurbine@f2a1c7f (atomicscience.process.turbine.TileElectricTurbine@f2a1c7f) is conflicting with atomicscience.process.turbine.TileElectricTurbine@654ec461 using the same position (already added, prev. te not removed, overlapping), aborting
2014-07-02 17:58:49 [WARNING] [IC2] EnergyNet.addTileEntity: atomicscience.process.turbine.TileElectricTurbine@15b4dda0 (atomicscience.process.turbine.TileElectricTurbine@15b4dda0) is conflicting with atomicscience.process.turbine.TileElectricTurbine@163ef03d using the same position (already added, prev. te not removed, overlapping), aborting 
2014-07-02 17:58:50 [WARNING] [Minecraft-Client] Memory connection overburdened; after processing 2500 packets, we still have 697 to go!

**Comment by davboecki** [comment] 2014-07-04 18:08
No, It's not the same one. I don't know why that is happening.

**Comment by AartBluestoke** [comment] 2014-07-06 22:03
Does toys happen on world load? Typically this is caused by trying to use a
pipe in tick 0, before the world has finished loading... If it is while
this world is running, than it still might be chunk load related, so ic2
might not have the init tick and request power from a pipe that has not yet
ticked, so isn't initialized correctly.

**Comment by ArtForz** [comment] 2014-07-06 22:08
@AartBluestoke: nope, that was something our powerprovider TE did wrong. 1a4266d02f230dbc034632d4c0cf3612fe2a179

**Comment by davboecki** [comment] 2014-09-08 21:39
I'm going to close this for now. If this happens again please open a new issue.

**Closed as completed by davboecki** 2014-09-08 21:39 UTC
