### ISSUE TITLE
Update Forestry proxy

### ISSUE THREAD

**Issue by Tsyklop** [RS485/LogisticsPipes#853] opened 2015-11-16 14:29 UTC
Error in log file http://pastebin.com/BSWL2A9B

logisticspipes-0.9.3.69

**Comment by davboecki** [comment] 2015-11-16 15:55
The forestry proxy didn't load. Please post your versions.

**Comment by Tsyklop** [comment] 2015-11-16 16:28
@davboecki forestry_1.7.10-4.1.1.46

**Comment by SonOfTheStars** [comment] 2015-11-16 18:53
seems like we have to update the Proxy Again @davboecki

**Comment by hron84** [comment] 2015-11-24 23:07
Forestry development got a mk3 speed upgrade as I see... :-)

**Comment by Zenopheus** [comment] 2015-12-19 02:12
Does anyone know what problems this might cause? Is there a work around until the problem is resolved?

**Comment by bziemons** [comment] 2016-02-15 11:19
Fixed in newest BC7 Stable for Forestry 4.2.x

**Closed as completed by bziemons** 2016-02-15 11:19 UTC
Labels: Bug
