### ISSUE TITLE
IllegalArgumentException @compareMethod when placing a pipe (not the first one)

### ISSUE THREAD

**Issue by jaeger0404** [RS485/LogisticsPipes#1078] opened 2016-11-27 17:56 UTC
Was playing few hours with logistic pipes and all worked fine. I was placing a ~100 Logistic Pipes with default route (a sorting System) and connecting them to the rest of the system, when the server crashed.
(just after placing the pipe which connects)
Crash-Report as attachement
[crash-2016-11-27_17.47.35-server.txt](https://github.com/RS485/LogisticsPipes/files/614872/crash-2016-11-27_17.47.35-server.txt)

**Comment by hron84** [comment] 2016-11-30 12:24
Could you make a screenshot from the elder system (or just that part where you connected to the new subsystem)?

**Comment by jaeger0404** [comment] 2016-12-03 18:30
red circle = connected pipe when crashing

pink circle = ~ 50 logistic pipes with 1 item input - not connected to system .. would be connected when placing pipe

green cirle = not in screenshot, rest of pipe system.. hundreds of connect bc pipes and a working logistic pipes system with another 100 pipes/suppliers/etc....

after setting "removeerrorentities" to true server started and let me place the logistics pipe again^^


New Error (should be new support ticket):
While writing this message, we build up a 600 blocks logistics pipe with power upgrades  and connected a BC:Quarry to it.
System seems to work, but not properly (items jump out of pipe). If we go near the Quarry all connections time out and the server won't let us connect.
After restarting the server we can connect to it, but it crashes again. After removing a pipe (disable Quarry and 600 pipes the connection won't time out...
Don't know if it's a BC Bug or LP Bug.

Thanks in advance
________________________________
Von: Gabor Garami <notifications@github.com>
Gesendet: Mittwoch, 30. November 2016 13:24
An: RS485/LogisticsPipes
Cc: Michael Spannbauer; Author
Betreff: Re: [RS485/LogisticsPipes] IllegalArgumentException @compareMethod when placing a pipe (not the first one) (#1078)


Could you make a screenshot from the elder system (or just that part where you connected to the new subsystem)?

-

**Comment by hron84** [comment] 2016-12-05 02:43
@jaeger0404 Sorry, but it seems like GitHub does not recognize attachments in emails.

**Comment by bziemons** [comment] 2020-06-16 22:33
Duplicate of #1075

**Closed as completed by bziemons** 2020-06-16 22:33 UTC
Labels: Bug, Duplicate, Crash
