### ISSUE TITLE
crash with buildcraft 6.3

### ISSUE THREAD

**Issue by Sailren** [RS485/LogisticsPipes#547] opened 2015-01-06 15:00 UTC
http://paste.ubuntu.com/9682508/

**Comment by loordgek** [comment] 2015-01-06 19:40
use 6.2.x

**Comment by TheOldOne822** [comment] 2015-01-06 20:11
LP blacklists newer versions even if it would otherwise work it deliberately crashes if the version number is newer

**Comment by Sailren** [comment] 2015-01-06 20:15
for what reason?

**Comment by asiekierka** [comment] 2015-01-06 20:41
@Sailren - BC 6.3 rewrote some pipe code and it would crash instantly if you tried to go around it. I know as I did.

**Comment by TheOldOne822** [comment] 2015-01-07 00:19
I don't know why the crash on version check is there but I do know more often then not it would crash anyway.

**Comment by bziemons** [comment] 2015-01-07 17:27
The crash is to prevent crashing you ingame and protect your saves from possible corruption. We do that, because an incompatible BC version does lead to a crash sooner or later anyway (as stated above).
Duplicate of #539 .

**Closed as completed by bziemons** 2015-01-07 17:27 UTC
Labels: Duplicate
