### ISSUE TITLE
Special Fluid Crafting Module/Pipe (Enhancement)

### ISSUE THREAD

**Issue by Rundas01** [RS485/LogisticsPipes#1517] opened 2020-08-20 19:10 UTC
Add a special kind of pipe or module which allows fluids to be the result of autocrafting operations.
For example you attach that pipe to a magma crucible to turn 1 redstone into 100mb of destabilized redstone.
But the amount of crafted fluid should be adjustable by millibuckets.
Would save space and makes more complex automation possible if you play a GregPack.

Alternatively you could also make the regular crafting module able to switch between item-/fluid output.

**Comment by bziemons** [comment] 2021-04-22 01:15
Duplicate of https://github.com/RS485/LogisticsPipes/discussions/1596

**Closed as completed by bziemons** 2021-04-22 01:15 UTC
