### ISSUE TITLE
Server/world load crash with interface and logistics pipe

### ISSUE THREAD

**Issue by SoulSkin** [RS485/LogisticsPipes#487] opened 2014-10-29 00:45 UTC
With a chassis pipe mk 3 with supplier and provider modules placed in the world, I placed a "multipart" interface (in the same block as a cable) beside the pipe which caused this crash:
http://pastebin.com/Uct99XHX

the server crashed and the world was unable to load until the interface was MCEdit-ed out of the world.
I believe this is caused by LP looking for the interface but finding the "multipart" TileEntity instead.

Using mod versions:
buildcraft - 6.0.18
logisticspipes - 0.8.1.71
appliedenergistics2 - rv2-alpha-14
forge - 1.7.10-10.13.1.1225

**Comment by SoulSkin** [comment] 2014-10-29 00:52
a full block interface on the same pipe did not cause a crash

**Comment by Kris1432** [comment] 2014-10-29 00:55
Courtesy of JamOORev

Edit: I dont know why I said that, but I look stupid on my picture.

**Comment by bziemons** [comment] 2014-10-29 17:11
Duplicate of #476.

**Closed as completed by bziemons** 2014-10-29 17:11 UTC
Labels: Duplicate
