### ISSUE TITLE
crafting module recipe

### ISSUE THREAD

**Issue by DrummerMC** [RS485/LogisticsPipes#594] opened 2015-02-23 20:19 UTC
the crafting module has no recipe

**Comment by SonOfTheStars** [comment] 2015-02-23 21:01
These modules are kind of untested and Beta-Content. If you want, grab MIneTweaker and add a recipe ;)
I also have a Modified version of LP handy wich adds recipes to them ;)

**Comment by bziemons** [comment] 2015-02-24 18:48
Duplicate of https://github.com/RS485/LogisticsPipes/issues/477 (yeah.. that was a while ago, sorry)

**Closed as completed by bziemons** 2015-02-24 18:48 UTC
Labels: Duplicate

**Comment by hron84** [comment] 2015-02-25 17:15
@bitterholz could you provide your recipes somewhere to users who wants to do beta testing?

**Comment by SonOfTheStars** [comment] 2015-02-25 22:41
you could allways cheat them in ;)
But if you relly want I could give you that Private Version Of LP when @davboecki  is OK with that.
But beware, it got some very new stuff in it wich im developing

**Comment by davboecki** [comment] 2015-02-25 23:03
As LP is under MMPL I'm totaly cool with it, and when I have some time I will add receipes for them into the 0.9 branch and make beta builds available for people to test.

**Comment by SonOfTheStars** [comment] 2015-02-25 23:19
Allright!

**Comment by SonOfTheStars** [comment] 2015-02-25 23:19
I need to sort out a few Bugs but ill put it op soon @hron84

**Comment by hron84** [comment] 2015-03-02 15:10
Cool, thanks
