### ISSUE TITLE
Crafting upgrade doesn't work on the Crafting request table

### ISSUE THREAD

**Issue by Doty1154** [RS485/LogisticsPipes#396] opened 2014-06-30 05:43 UTC
Another [Enhancement], for the crafting request table when you apply a crafting fuzzy upgrade instead of having to request the correct type of steel you could just use the current steel in the system. when requesting.

Thanks for the awesome mod...

**Comment by bziemons** [comment] 2014-10-21 18:29
This is a duplicate of #176. I am just cleaning things up ;)

**Closed as completed by bziemons** 2014-10-21 18:29 UTC
Labels: Duplicate
