### ISSUE TITLE
Logistics HUD

### ISSUE THREAD

**Issue by megamanzteam** [RS485/LogisticsPipes#58] opened 2013-04-28 01:49 UTC
I tested with build 407 and the displays will not render. I don't know if it is due to being a Dev. build and has not been implemented yet or if it is an unknown issue yet. So if you guys are aware you can ignore this report.

**Comment by davboecki** [comment] 2013-04-28 13:34
Can't reproduce. For me they work fine.

**Comment by megamanzteam** [comment] 2013-04-28 15:37
I managed to see errors from MultiMC's console. I uploaded the log, perhaps that can help? http://www.mediafire.com/view/?22cabl6smlia4ed

**Comment by davboecki** [comment] 2013-04-28 16:35
Ok thanks for that. I now know where the bug is thanks. will be fixed soon.

**Closed as completed** 2013-05-03 14:33 UTC
