### ISSUE TITLE
Crash when placing autarchic gate on LP.

### ISSUE THREAD

**Issue by olee** [RS485/LogisticsPipes#681] opened 2015-05-19 14:43 UTC
Yes, I did something not very intelligent...

Placing an autarchic gate on a LP will make the BC transport system crash and then kicks all players from the server (who are near the location of the pipe only?), until the server is restarted (after using a backup from some minutes ago).

On the LP in the middle of the screen under the MFR unifier is where I placed the diamond autarchic gate and after configuring it to a pulsating gate, it caused the issue.

This is the crash log:

```
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]: java.lang.NullPointerException
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at logisticspipes.proxy.buildcraft.robots.LPRobotConnectionControl.checkAll(LPRobotConnectionControl.java:58)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at logisticspipes.proxy.buildcraft.subproxies.LPBCTileGenericPipe.updateEntity_LP(LPBCTileGenericPipe.java:182)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at logisticspipes.asm.wrapper.BCTilePartProxyWrapper.updateEntity_LP(.LP|ASM.dynamic:172)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:204)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.World.func_72939_s(World.java:1939)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
[STDERR]: [java.lang.Throwable$WrappedPrintStream:println:748]:         at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
[LogisticsPipes]: Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception
```

**Comment by bziemons** [comment] 2015-05-19 15:25
Would you mind giving us some version information about Forge, LP and BC?

**Comment by davboecki** [comment] 2015-05-19 19:10
And could you also upload your full server log to https://gist.github.com?

**Comment by SonOfTheStars** [comment] 2015-05-19 19:39
Im having no Problems with putting Gates on my Pipes (LP 0.9.100)

**Comment by olee** [comment] 2015-05-19 22:24
1. Full server log would need a bit of time to find and there is no useful information left in it except loaded mods and versions. However as this issue has only to do with BC + LP, there's not much need for it... If they are really needed though, I can try to find it.
2. BC version 6.4.15
3. LP version 0.9.0.91

**Comment by davboecki** [comment] 2015-05-19 22:33
I'm sorry to say that there is a reason why I asked for the full logs. What you posted is only a printed exception that is caught by our mod proxy system. See:
`[LogisticsPipes]: Disabled BCProxy for Mod: BuildCraft|Transport. Cause was an Exception`
That shouldn't crash and kick all players. So there has to be more than just that exception.

**Comment by olee** [comment] 2015-05-20 00:23
Nice try, but **no**.
There is nothing other than this one exception.
Feel free to confirm it yourself... https://gist.github.com/olee/e634320e5a254bf6694e

**Comment by bziemons** [comment] 2015-05-20 06:23
You must be new to OpenSource communities, because we are nice when it comes to talking to each other. You have the option to be nice and we will be nice and solve the issue together or you do not want to help us solve this issue.
It's your choice. And I will not discuss this.

**Comment by davboecki** [comment] 2015-05-20 09:00
Yes, you are correct. There is nothing inside the server log. But that still shouldn't be the reason the client disconnected. Is there anything inside the client log.

**Comment by olee** [comment] 2015-05-20 12:03
@theZorro266 sorry I didn't mean to be rude
It's more the other way round. Because I myself develop for a MC mod, I know what I am talking about and that's why I said "there's nothing else in the log" - that "nice try" was meant more like a joke and in no way offending. When we have issues in FE we have the same problem with people not pasting their full logs and sometimes cutting off important information which is why I thought about it in a funny way :wink: 

@davboecki Yeah I totally missed to check the client log
Should have attached it from the beginning of course... :weary: 
https://gist.github.com/olee/def56dc609be2eb9f73d
(Log starts at the time where the gate was placed and ends just after the connection completely closed)
Looks like an exception in the net packet...
If you need more information, just ask.
But I don't think there is any input left that I could provide you....

**Comment by davboecki** [comment] 2015-05-20 16:10
Thanks for checking the client. That log should be all I need. Already know what two bugs this are. WIll fix them as soon as I get the time.

**Comment by bziemons** [comment] 2015-06-08 23:37
@olee could you retest it with latest 0.9.1 ? I might have accidentally fixed it.

Edit: Or at least I cannot reproduce it

**Comment by davboecki** [comment] 2015-06-09 18:42
The actual crash is fixed by this: https://github.com/RS485/LogisticsPipes/commit/9cb5f4845ff6bda480a1467a672e33f95d4fc12e

**Closed as completed** 2015-06-09 18:59 UTC
Labels: Bug
