### ISSUE TITLE
broken textures 1.12.2

### ISSUE THREAD

**Issue by Spenny519** [RS485/LogisticsPipes#1210] opened 2019-03-17 16:18 UTC
the textures on the pipes break when thaumcraft is installed
![2019-03-17_09 16 28](https://user-images.githubusercontent.com/36276355/54494265-8d551080-4895-11e9-9c89-0410342a510a.png)

**Comment by ghost** [comment] 2019-03-23 14:40
are you using some texture pack?

**Comment by Spenny519** [comment] 2019-03-24 04:32
no

**Comment by Spenny519** [comment] 2019-03-24 04:32
I figured out the reason. it only happens when I reload the textures

**Comment by ghost** [comment] 2019-03-24 15:25
Exactly. It happens to me too

**Comment by davboecki** [comment] 2019-03-24 15:45
Duplicate of https://github.com/RS485/LogisticsPipes/issues/1186

**Closed as completed by davboecki** 2019-03-24 15:45 UTC
Labels: Duplicate
