### ISSUE TITLE
Logistic network not working through phase(Teleport pipes)

### ISSUE THREAD

**Issue by Da-Technomancer** [RS485/LogisticsPipes#724] opened 2015-06-28 14:32 UTC
This problem occurs even when the pipes are set to send/receive and there are only 2 teleport pipes total.

**Comment by hron84** [comment] 2015-06-29 07:19
@Da-Technomancer Could you please provide a bit more information about your system? First, we need your Forge, BuildCraft (if installed) and LogisticsPipes versions and - if it is possible - some screenshots about your system and about the issue. It would be really help the investigation of the issue and can speed up the development of the fix for your issue.

**Comment by bziemons** [comment] 2015-06-29 15:31
Not needed. This is a duplicate of #348

**Closed as completed by bziemons** 2015-06-29 15:31 UTC
Labels: Duplicate
