### ISSUE TITLE
NPE with BCPipeInformationProvider

### ISSUE THREAD

**Issue by micmou** [RS485/LogisticsPipes#738] opened 2015-07-11 18:13 UTC
I am currently running Logistics Pipes 0.10.0.5 and every time any of my players approach certain buildcraft buildings with Logistics Pipes things in them we get server crash here is the log

http://pastebin.com/pEzRje60

We are running CauldronNG on Debian 8.1 running Java 8u_45 and I can confirm that this issues happens to more than one server and not in forge. The resonant rise people told me and some others to report yo you and I did not see any other posts and though I would post here.

PS. I am not familiar with tagging issues so...

**Comment by bziemons** [comment] 2015-07-11 19:07
Duplicate of #727. Please downgrade to 0.9.1.x for bc7 and maybe tell RR that 0.10 is the unstable version.

**Closed as completed by bziemons** 2015-07-11 19:07 UTC
Labels: Duplicate

**Comment by Lanse505** [comment] 2015-07-12 15:58
@theZorro266 Quick Question; Where are your 0.10 stable version located, cause they are not on Jenkins for BC7, aswell as I can't find them under your releases section on github. So Where are they hosted?

**Comment by bziemons** [comment] 2015-07-12 16:15
@Lanse505 see https://github.com/RS485/LogisticsPipes/issues/719#issuecomment-120434761

**Comment by Lanse505** [comment] 2015-07-12 16:22
Ah, Well i derped.
