### ISSUE TITLE
Display tooltip for crafting modules to show what receipt is encoded

### ISSUE THREAD

**Issue by mikiones** [RS485/LogisticsPipes#1268] opened 2019-06-16 14:14 UTC
when you have bunch of crafted cards in inv is hard to find out what receipt is encoded. 
you will need open it to see

provide more confident way to see receipt encoded on card in user inventory and mk_x pipes

**Comment by bziemons** [comment] 2020-06-10 18:15
Duplicate of #869

**Closed as completed by bziemons** 2020-06-10 18:15 UTC
Labels: Duplicate, Enhancement
