### ISSUE TITLE
Crash Client/Server on Ticking block entity

### ISSUE THREAD

**Issue by Berserker2K3** [RS485/LogisticsPipes#498] opened 2014-11-06 05:57 UTC
Test-Enviroment
Chest with connectect Chassis with Extractor Module
AE-Interface with connected Chassis with Item Sink Module (Default Route: yes)

Minecraft: 1.7.10
Client-Forge 1.7.10 1231
Applied Energistics: 2 RV1 Stable1
Buildcraft: 6.1.5
Power: Mekanism 7.1.122 (Energy Cube)
Server: Cauldron 1.7.10 (Forge 1231)

client crashes if i put items in the chest

---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 11/6/14 6:51 AM
Description: Ticking block entity

java.lang.IllegalArgumentException: The direction must not be unknown
        at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.<init>(AEInterfaceInventoryHandler.java:42)
        at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.getUtilForTile(AEInterfaceInventoryHandler.java:70)
        at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:48)
        at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:59)
        at logisticspipes.utils.InventoryUtilFactory.getInventoryUtil(InventoryUtilFactory.java:55)
        at logisticspipes.pipes.basic.CoreRoutedPipe.getSneakyInventory(CoreRoutedPipe.java:1469)
        at logisticspipes.pipes.basic.CoreRoutedPipe.getSneakyInventory(CoreRoutedPipe.java:1461)
        at logisticspipes.modules.ChassiModule.sinksItem(ChassiModule.java:68)
        at logisticspipes.logistics.LogisticsManager.canSink(LogisticsManager.java:167)
        at logisticspipes.logistics.LogisticsManager.getBestReply(LogisticsManager.java:119)
        at logisticspipes.logistics.LogisticsManager.hasDestination(LogisticsManager.java:73)
        at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:1505)
        at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:124)
        at logisticspipes.modules.ModuleExtractor.tick(ModuleExtractor.java:153)
        at logisticspipes.modules.ChassiModule.tick(ChassiModule.java:118)
        at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:423)
        at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:180)
        at net.minecraft.world.World.func_72939_s(World.java:2477)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
        at java.lang.Thread.run(Thread.java:745)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
        at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.<init>(AEInterfaceInventoryHandler.java:42)
        at logisticspipes.proxy.specialinventoryhandler.AEInterfaceInventoryHandler.getUtilForTile(AEInterfaceInventoryHandler.java:70)
        at logisticspipes.utils.InventoryUtilFactory.getUtilForInv(InventoryUtilFactory.java:48)
        at logisticspipes.utils.InventoryUtilFactory.getHidingInventoryUtil(InventoryUtilFactory.java:59)
        at logisticspipes.utils.InventoryUtilFactory.getInventoryUtil(InventoryUtilFactory.java:55)
        at logisticspipes.pipes.basic.CoreRoutedPipe.getSneakyInventory(CoreRoutedPipe.java:1469)
        at logisticspipes.pipes.basic.CoreRoutedPipe.getSneakyInventory(CoreRoutedPipe.java:1461)
        at logisticspipes.modules.ChassiModule.sinksItem(ChassiModule.java:68)
        at logisticspipes.logistics.LogisticsManager.canSink(LogisticsManager.java:167)
        at logisticspipes.logistics.LogisticsManager.getBestReply(LogisticsManager.java:119)
        at logisticspipes.logistics.LogisticsManager.hasDestination(LogisticsManager.java:73)
        at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:1505)
        at logisticspipes.pipes.basic.CoreRoutedPipe.hasDestination(CoreRoutedPipe.java:124)
        at logisticspipes.modules.ModuleExtractor.tick(ModuleExtractor.java:153)
        at logisticspipes.modules.ChassiModule.tick(ChassiModule.java:118)
        at logisticspipes.pipes.basic.CoreRoutedPipe.updateEntity(CoreRoutedPipe.java:423)
        at logisticspipes.pipes.basic.LogisticsTileGenericPipe.func_145845_h(LogisticsTileGenericPipe.java:180)

-- Block entity being ticked --
Details:
        Name: logisticspipes.pipes.basic.LogisticsTileGenericPipe // logisticspipes.pipes.basic.LogisticsTileGenericPipe
        Block type: ID #838 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
        Block data value: 0 / 0x0 / 0b0000
        Block location: World: (709,78,887), Chunk: (at 5,4,7 in 44,55; contains blocks 704,0,880 to 719,255,895), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
        Actual block type: ID #838 (tile.null // logisticspipes.pipes.basic.LogisticsBlockGenericPipe)
        Actual block data value: 0 / 0x0 / 0b0000
        LP-Version: 0.8.2.77:false
        Pipe: logisticspipes.pipes.PipeLogisticsChassiMk1
        Transport: logisticspipes.transport.PipeTransportLogistics
        Router: ServerRouter: {ID: 10, UUID: d9e86740-3686-481d-aaa0-0e38205e80dd, AT: (0, 709, 78, 887), Version: 13), Destroied: false}
        stillNeedReplace: false
Stacktrace:
        at net.minecraft.world.World.func_72939_s(World.java:2477)
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

**Comment by AartBluestoke** [comment] 2014-11-06 06:44
it looks like instead of "unknown" direction, we need to work out what side we are actually on, and "sneak" from the correct side

**Comment by bziemons** [comment] 2014-11-13 17:56
Duplicate of #481

**Closed as completed by bziemons** 2014-11-13 17:56 UTC
Labels: Duplicate
