### ISSUE TITLE
Crafting Module not saving recipe with GTCE machines

### ISSUE THREAD

**Issue by TroubledCodes** [RS485/LogisticsPipes#1642] opened 2021-08-05 18:14 UTC
I am having issues saving the craft after exiting the module screen, and when going back in it just displays a blank crafting space.
This specifically is happening with the Assembler

**Comment by TroubledCodes** [comment] 2021-08-05 18:17
![2021-08-05_13 14 37](https://user-images.githubusercontent.com/80348699/128400615-f4c6eef5-7acb-4911-b447-c86a93714364.png)
![2021-08-05_13 14 42](https://user-images.githubusercontent.com/80348699/128400617-8740e2e9-477e-4acf-bdc8-f65e5dd81b01.png)
These are the screenshots of putting a craft in the module and after exiting and reentering

**Comment by TroubledCodes** [comment] 2021-08-05 18:18
The wrench was messing up the craft, nevermind

**Comment by TroubledCodes** [comment] 2021-08-05 18:32
Welp, it still isnt working :(

**Comment by T3M8029** [comment] 2022-06-12 19:15
GTCE isn´t at fault here, the problem is between JEI and LP, if you drag an item from JEI and the use the scrollwheel to change the amount of said item, it isn´t going to be saved, so you have to have the item in your inventory for it to save. This bug is mostly fixed in the[ new version ](https://www.curseforge.com/minecraft/mc-mods/logistics-pipes/files/3298772). Probably a bit late, but at least people with the same problem can see this and it will help them out.

**Comment by bziemons** [comment] 2022-09-09 17:09
Seems like a duplicate of #1612 and is therefore fixed in version 0.10.4.12.

**Closed as completed by bziemons** 2022-09-09 17:09 UTC
