### ISSUE TITLE
[1.12.2] LogisticsPipes can't see into AE2 inventory

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1218] opened 2019-04-07 19:02 UTC
Logistics Pipes can put into AE2 inventory but it can't see into. 
Video of my setup:  https://www.youtube.com/watch?v=UeKCG-r8d6E

**Comment by bziemons** [comment] 2019-04-09 11:02
This is a duplicate of #1204

**Closed as completed by bziemons** 2019-04-09 11:02 UTC
Labels: Duplicate
