### ISSUE TITLE
Crash with OreDict tools in crafting pipes

### ISSUE THREAD

**Issue by Timeslice42** [RS485/LogisticsPipes#939] opened 2016-03-15 15:33 UTC
In logistic crafting table recipes that have a tool as part of the recipe (one that isn't used up) that is set to use the oredict a crash occurs when requesting that recipe. This worked in 50c4339 which fixed #922.

Here is the setup: https://i.imgur.com/UL5Vj5W.png
Here is the relevant part of the crash log: http://paste.ee/p/qPVUv

This is using LP 0.9.3.99. Also I tried it without the crafting cleanup card, and with IgnoreNBT, neither worked.

**Comment by davboecki** [comment] 2016-03-15 15:45
Would you be able to provide me with a world download? That crash is an error that has been around for a long time and I haven't been able to track it down because I can't reproduce it.

**Comment by Timeslice42** [comment] 2016-03-15 15:53
Sure... may take a few to upload.

**Comment by SonOfTheStars** [comment] 2016-03-15 16:15
Youre storing Items inside Storage Drawers or AE right?
@davboecki we have a Ordeict crash when requesting from AE or SD Storages

**Comment by Timeslice42** [comment] 2016-03-15 16:16
I do have LP connected to an AE2 interface, but the tool in question is not in AE. (In fact none of the parts are, but that doesn't necessarily mean that's not part of the crash.)

**Comment by Timeslice42** [comment] 2016-03-15 16:16
https://www.dropbox.com/s/8ljoksa13pezzco/LP-I939.zip?dl=0

Okay, this is just about everything. I'm using forge build 1566 (which you'll probably have to manually add). Also, optifine is installed with multi-core chunk loading, so you'll want to either disable threaded optimization on your video card, or the multi-core chunk rendering. The recipe in question is the stone gear recipe, which I believe you'll be looking directly at. The crafting tools normally get cleared into that chest to the right, but I think I don't currently have the crafting cleanup upgrade installed on that pipe.

I removed the other worlds and their backups, but I left all of the log files in there. Since you aren't using the direct FTB version of the pack (I've modified it anyways) you may get the "missing texture" texture for the background of the main menu, but everything else should work fine. Let me know if you have any questions/problems.

P.S. Issue 891 has been updated with the correct log, due thanks in part to theZorro, although I no longer use that setup in this world (for obvious reasons).

**Comment by SonOfTheStars** [comment] 2016-03-15 16:34
Additionally, requesting anything with an Ordeict modifier on the Crafting Pipe out of either AE or Storage Drawers restults in an Internal Server Error.

This applies for all except DMG-Ignore is far as ive tested. OrdeDict, OrePrefix and NBT-Ignore are allways resulting in getting thrown of the server

**Comment by SonOfTheStars** [comment] 2016-03-15 16:37
oh BTW @Timeslice42 if you use damagable items in the recipe, you dont need to request them every time. just leave them in the Table and set the table to ignore DMG should work

**Comment by Timeslice42** [comment] 2016-03-15 16:38
lol, I wish. The crafting tables don't check their own inventory first when looking for items, and the GT tools don't store damage in metadata anyways.

**Comment by SonOfTheStars** [comment] 2016-03-15 16:49
You need to leave out the Tool in the Pipe. just put it in the recipe and store it inside the table. If everything works the way it should, itll craft

**Comment by bziemons** [comment] 2016-03-15 16:51
Duplicate of #784, #881, #739

**Comment by Timeslice42** [comment] 2016-03-15 16:51
Why didn't I ever think of that? The crafting pipe is just a messenger anyways, it's the crafting table that does the actual work. The only problem with that is that I'll never be notified when the tool breaks. The crafting request will just silently hang forever.

**Closed as completed by bziemons** 2016-03-15 16:51 UTC
Labels: Bug, Duplicate

**Comment by Timeslice42** [comment] 2016-03-15 16:59
@theZorro266 Confirmed that this issue does not happen if I don't have a provider pipe on my AE2 interface (even though none of the materials were in AE anyways).

**Comment by bziemons** [comment] 2016-03-15 17:03
@Timeslice42 that's good to know and might help finding that issue.

**Comment by SonOfTheStars** [comment] 2016-03-15 17:06
Apparently all Fuzzy request bust the interaction with AE and SD. Even if nothing actually gets Pulled.
Has to be in the Check for availability.

**Comment by davboecki** [comment] 2016-03-25 15:40
https://github.com/RS485/LogisticsPipes/commit/ce7e4d7e0a03e03f9a527371f70d2d55764df339

**Comment by SonOfTheStars** [comment] 2016-03-25 15:44
@davboecki does this fix Oredict Crafting from AE and SD as well?

**Comment by davboecki** [comment] 2016-03-25 20:26
It wasn't specifiy to AE and SD but the condition "that one provider module would handle several types that matched the OreDict description" was more likely. So that should be fixed now as well.
