### ISSUE TITLE
Missing recipes of crafter modules and active supplier

### ISSUE THREAD

**Issue by GMNPeojects** [RS485/LogisticsPipes#553] opened 2015-01-20 08:15 UTC
Impossible to create crafting modules and active supplier
Missing recipes declaration in LogisticsPipes/common/logisticspipes/recipes/RecipeManager.java

**Comment by bziemons** [comment] 2015-01-21 19:32
Duplicate of #477

**Closed as completed by bziemons** 2015-01-21 19:32 UTC
Labels: Duplicate
