### ISSUE TITLE
CC error when using getAvailableItems()

### ISSUE THREAD

**Issue by RikuSS4** [RS485/LogisticsPipes#304] opened 2014-04-14 10:20 UTC
Using Computercraft version 1.62. I attached a logistic pipe to a turtle and connect it and use the getAvailableItems() command. I get the following error:

`2014-04-14 02:10:25 [INFO] [STDERR] java.lang.IllegalArgumentException: object is not an instance of declaring class
2014-04-14 02:10:25 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2014-04-14 02:10:25 [INFO] [STDERR]     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2014-04-14 02:10:25 [INFO] [STDERR]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2014-04-14 02:10:25 [INFO] [STDERR]     at java.lang.reflect.Method.invoke(Unknown Source)
2014-04-14 02:10:25 [INFO] [STDERR]     at logisticspipes.proxy.cc.LPTilePipeWrapper$1.call(LPTilePipeWrapper.java:333)
2014-04-14 02:10:25 [INFO] [STDERR]     at logisticspipes.ticks.QueuedTasks.tickEnd(QueuedTasks.java:44)
2014-04-14 02:10:25 [INFO] [STDERR]     at cpw.mods.fml.common.SingleIntervalHandler.tickEnd(SingleIntervalHandler.java:34)
2014-04-14 02:10:25 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.tickEnd(FMLCommonHandler.java:141)
2014-04-14 02:10:25 [INFO] [STDERR]     at cpw.mods.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:282)
2014-04-14 02:10:25 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:677)
2014-04-14 02:10:25 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:587)
2014-04-14 02:10:25 [INFO] [STDERR]     at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:129)
2014-04-14 02:10:25 [INFO] [STDERR]     at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
2014-04-14 02:10:25 [INFO] [STDERR]     at net.minecraft.server.ThreadMinecraftServer.run(SourceFile:583)
2014-04-14 02:10:27 [WARNING] [LogisticsPipes|Main] CC call getAvailableItems on logisticspipes.pipes.PipeItemsRequestLogistics at (-978,4,738) took too long.`

Same type of error message from getCraftableItems(). The Computercraft program just stops with an error pointing to the line that called the command and "Took too long."

**Comment by davboecki** [comment] 2014-04-14 15:03
Will look into that, but I think I already know what the problem is.

**Comment by davboecki** [comment] 2014-04-15 20:24
Should be fixed now.

**Closed as completed by davboecki** 2014-04-15 20:24 UTC
