### ISSUE TITLE
OreDict ItemSink module can't save ore_dict

### ISSUE THREAD

**Issue by wstc1997** [RS485/LogisticsPipes#1673] opened 2022-10-06 05:27 UTC
When I added OreDict in the OreDict ItemSink module, and opened it again, it returned to its original state and couldn't save the OreDict I set。

I set
![image](https://user-images.githubusercontent.com/60385450/194221462-4bb7c00f-be70-4867-b092-0c0c69af0f67.png)

open again
![image](https://user-images.githubusercontent.com/60385450/194221571-39018397-38be-491b-bc62-6b379e3e7a79.png)

**Comment by bziemons** [comment] 2022-10-06 15:47
Hey, yeah, sorry about this. It is a duplicate of #1609 and should be fixed soon.

**Closed as completed by bziemons** 2022-10-06 15:47 UTC
Labels: Bug, Duplicate
