### ISSUE TITLE
Problem with Teleportpipes from additionalpipes mod

### ISSUE THREAD

**Issue by ghosty1911** [RS485/LogisticsPipes#485] opened 2014-10-27 17:36 UTC
Hello
There is a problem withe the teleportpips from theadditionalpipes mod
( https://github.com/tcooc/AdditionalPipesBC/pull/104 )

The teleportpips works fine.
The problem is that i must use a normal bildcraft pipe between the teleportpipe and the basic LP-pipe.
when i use the LP-pipe befor the teleportpipe the items dropt out.
The LP-Power system works with it and it´s woks multiworld too.
So you can´t port EU-Power or RF-Power with it

I use latest LP Build and Buildcraft 6.1.1

**Comment by bziemons** [comment] 2014-10-27 19:28
Duplicate of #348

**Closed as completed by bziemons** 2014-10-27 19:28 UTC
Labels: Duplicate
