### ISSUE TITLE
NPE Crash with MrTPJ Forge relocation

### ISSUE THREAD

**Issue by michelegargiulo** [RS485/LogisticsPipes#752] opened 2015-07-23 14:46 UTC
I set up a simple LP network, where an extractor mk3 extracts from an ender chest items, then if they match the filter of one of the two oreDict itemsink modules in a chassis mk5 will go into an iron chest (for ore processing), else they will go to the default route in a ME interface. I set that up a couple days ago, and now it is the first time it crashes (randomly). reading the crash report (I'm a noob) it seems that logistics pipes tried to render an object of Forge relocation (by MrTPJ) and failed to do so. So it seems strange, since I never touched that mod yet.

Using:
Logisitcs pipes 0.9.1.15
Buildcraft 7.0.16
Buildcraft Compat 7.0.9

CrashReport: http://pastebin.com/LRZvDhXt

**Comment by davboecki** [comment] 2015-08-05 11:39
I couldn't reproduce this. Even when moving unrouted pipes with the relocation frames.

**Comment by michelegargiulo** [comment] 2015-08-05 15:51
The crash didn't happen moving pipes, my system was running And then randomly crashed. Maybe some sort of item/block of  forge relocation crashes the game when rendered through a logistics pipe. Have you tried to move every item/block of forge relocation using logistics pipes? I'm sorry I can't be more detailed, but i was far away from my (chunkloaded) base when The crash happened.

**Comment by bziemons** [comment] 2015-08-08 02:38
Fixed in 93e35de44678c37699a1f9a4aa2d49f03faea286, will be merged to BC7 tomorrow.

**Closed as completed** 2015-08-08 15:46 UTC
Labels: Bug
