### ISSUE TITLE
Crafting Stops If Inventory Is Full

### ISSUE THREAD

**Issue by FeedCat02** [RS485/LogisticsPipes#1291] opened 2019-06-22 18:37 UTC
If you request something to craft and the inventory of that machine is full, the items are sent to the machine and go back to storage but never get resent when the inventory empties

**Comment by FeedCat02** [comment] 2019-06-23 08:11
![2019-06-23_09 08 49](https://user-images.githubusercontent.com/45899252/59973333-a8bb7000-9596-11e9-914e-1ccafc0a1641.png)
Iron sent to make coils got sent and coils were made, glass was sent to make the pipes (in the same machine) and came back cause the iron was there but the glass is never resent

**Comment by FeedCat02** [comment] 2019-06-23 08:21
but it only happens in non-vanilla machines

**Comment by bziemons** [comment] 2019-06-29 09:31
Can't reproduce this with e.g. TE machines. What machines are you using?

**Comment by FeedCat02** [comment] 2019-06-30 07:21
If you are making for example mixed metal ingots from ic2 (2 iron plate, 2 bronze plates, 2 tin plates) it will send the 2 of each of those ingots to the TE compactor but only 1 type will enter and the other 2 types of ingot will not be sent.  Then if you decide to move the ingots into the machine manually the craft finishes then it sends more ingots to the compactor even though the craft is finished

**Comment by FeedCat02** [comment] 2019-06-30 07:22
Logistics pipes wont send to already full inventories, but if 2 things are trying to enter at the same time then problems occur

**Comment by Turmfalke2** [comment] 2019-07-14 10:22
Not sure what more you need here, but here is a simple setup to demonstrate it.
![2019-07-14_12 12 03](https://user-images.githubusercontent.com/5174562/61182250-ef9a0400-a630-11e9-9920-783a0167b37a.png)

The chest in on the left side has several stacks of copper and tin ingots. It is attached with a chassis mk2 with a provder and item sink module. The item sink module is set to default. 
The block in the middle is a basic wiremill from GTCE, it has an mk2 chassis with a recipe for 1 copper ingot -> 2 copper wires and 1 tin ingot -> 2 tin wires.

If I now request 10 copper and tin wires in the request table at the bottom I can see 2 packages leaving the chest on the left. The one with the 5 tin ingots reaches the machine a moment earlier, enters it and gets turned into 10 tin wires that are send to the table.
The 5 copper ingots bounce back to the steel chest and then remain there forever.

If I then manually insert the copper ingots directly into the wiremill the resulting wires are extracted immediately. After the fifth ingot entering the machine and crafting pipe pulling the last wire the lp networks sends the 5 ingot from earlier to the wiremill, but the crafting pipe isn't expecting them anymore and resulting wires just remain in the mill.

logisticspipes-0.10.2.153.jar
gregtech-1.12.2-1.8.3.416.jar

**Comment by FeedCat02** [comment] 2019-07-15 16:44
exactly the problem (consistent with other mods as well)

**Comment by bziemons** [comment] 2019-07-15 17:36
I haven't been able to reproduce this yet, but we'll try more

**Comment by hubertnnn** [comment] 2019-07-18 11:54
If I remember correctly there used to be an advanced version of crafting pipes/modules that stores internally excess items (instead of spitting them on floor as the old version used to do). Are those no longer a thing?

**Comment by bziemons** [comment] 2019-07-18 22:20
those are no longer a thing and will be replaced by some buffer mechanic in the future

**Comment by bziemons** [comment] 2020-08-08 08:15
Fixed by https://github.com/RS485/LogisticsPipes/commit/8d2a4fe08d46255211c3674299f4176a09af7792

**Closed as completed by bziemons** 2020-08-08 08:15 UTC
Labels: Bug
