### ISSUE TITLE
ThermalExpansion Tesseracts between Worlds

### ISSUE THREAD

**Issue by ghosty1911** [RS485/LogisticsPipes#475] opened 2014-10-22 13:51 UTC
ThermalExpansion Tesseracts work only in one World but not for example form normal World to Nether, the Power don´t connect.
I don´t realy sure its a problem from LP but the Tesseracts works between Overworld and Nether.
I use LP version 71

**Comment by bziemons** [comment] 2014-10-22 15:28
I marked it as a bug, but right now I do not know on which side the problem is.

**Comment by ghosty1911** [comment] 2014-10-22 15:34
i have test the Tesseracts with Energy Cells between the worlds, that works

**Comment by ghosty1911** [comment] 2014-10-26 10:31
Hello
So i have test some more...
With the latest version of additionalpipes (3.1) it´s works fine between the dimensions the only problem there is that the teleportpips don´t transmit the IC ore RF power that not work.
And i must use a normal pipe before the teleportpipe to send items, when i use a basic LP pipe befor the teleportpipe the items drop out and will not portet

**Comment by ghost** [comment] 2015-01-28 13:55
That still happens in version 0.8.3.91

I have a logistics inventory connector back at my base connected to a tesseract set to input and output items(transfer both ways). I placed another tesseract in the same dimension as my base(with the same config as previous) and placed a request logistics pipe mark II on top of it. The pipe gets power and i'm able to access my items. When i move the second tesseract in the end, the pipes no longer get powered and i cant access my items.

The only way I found around this is with remote oderers, chests and complex systems...

**Comment by davboecki** [comment] 2015-01-30 11:47
Should be fixed.

**Closed as completed by davboecki** 2015-01-30 11:47 UTC
Labels: Bug, Needs Comments
