### ISSUE TITLE
Server crash with AE Interfaces connection

### ISSUE THREAD

**Issue by JasonMcRay** [RS485/LogisticsPipes#476] opened 2014-10-23 13:53 UTC
Our development server has crashed with following crash: http://pastebin.com/Uct99XHX
It also crashes immediately after world is loaded, so we are unable to start it at the moment.

One of my players was messing with LP Provider module in Chassi pipe connected to AE2 interface. So possible issue in here.

LP: v0.8.1.68
AE2: Stable RV1
Forge: 10.13.1.1223

**Comment by JasonMcRay** [comment] 2014-10-23 14:06
Tested also version 0.8.1.72 still crashes on load

**Comment by bziemons** [comment] 2014-10-23 15:59
Actually, I cannot reproduce that crash. I am running on a similar LP version and AE2 rv1-beta-27

**Comment by JasonMcRay** [comment] 2014-10-23 18:03
Trying to reproduce it in my instance. Will let you know the results

**Comment by JasonMcRay** [comment] 2014-10-23 19:13
Tried to reproduce, but I am unable to make it crash again. Probably random issue

**Comment by bziemons** [comment] 2014-10-23 19:34
Can you put the newest version, which is coming with the commit mentioned above, on your server and put the crashlog on pastebin.com, if a crash happens again?

**Comment by JasonMcRay** [comment] 2014-10-25 15:34
Sure. But its not showing up on the Jenkins. Its showing as failed build and latest is still .72

**Comment by davboecki** [comment] 2014-10-25 15:47
Builds are fixed now.

**Comment by JasonMcRay** [comment] 2014-10-25 16:48
Nice. Got the version and if we will crash again, will post a crashlog.
Thanks

**Comment by bziemons** [comment] 2014-10-25 22:37
Probably the same problem as with #481, i.e. it doesnt matter what module.

**Comment by davboecki** [comment] 2014-11-13 23:28
Should be fixed by build 80.

**Closed as completed by davboecki** 2014-11-13 23:28 UTC
Labels: Bug
