### ISSUE TITLE
MFR harvester not connecting to basic logistics pipes

### ISSUE THREAD

**Issue by AartBluestoke** [RS485/LogisticsPipes#451] opened 2014-09-17 06:32 UTC
as seen on the rs485 server, forgot to create this issue after noticing it; stone connects, mfr doesn't connect to a basic logistcs pipe in the same location.

**Comment by loordgek** [comment] 2014-09-21 11:42
rs485 server? can i join?

**Comment by bziemons** [comment] 2014-10-21 19:01
@loordgek I guess you are wrong here in the issues section.

And yup, something is weird with the Harvester and non-liquid LP pipes.

**Comment by davboecki** [comment] 2014-10-24 22:54
Caused by IPipeConnection.ConnectOverride.CONNECT being ignored.

**Comment by davboecki** [comment] 2014-11-02 02:08
Will be fixed with the release for BC 6.1.5.

**Closed as completed** 2014-11-02 11:40 UTC
Labels: Bug
