### ISSUE TITLE
sneaky upgrade causes crash

### ISSUE THREAD

**Issue by stevee-bee** [RS485/LogisticsPipes#1686] opened 2023-03-17 06:07 UTC
Crash (https://mclo.gs/urmS99b) occurs when attempting to configure a Sneaky Upgrade with a Pipe Controller on a MK1 Chassis Pipe connected to the top of a Red Matter Furnace.

I've realized the Chassis Pipe with the Crafting Module is still supposed to be at the bottom of the furnace. After making this change, the crash still occurs (https://mclo.gs/GicO9Hb) when clicking on the config for the Sneaky Upgrade. The 3D display of the furnace is briefly displayed and then it crashes.

**Comment by bziemons** [comment] 2023-03-17 10:58
Duplicate of https://github.com/RS485/LogisticsPipes/issues/1674 fixed in version 0.10.4.34.

**Closed as completed by bziemons** 2023-03-17 10:58 UTC
Labels: Duplicate
