### ISSUE TITLE
crafting module visual bug

### ISSUE THREAD

**Issue by Nex4rius** [RS485/LogisticsPipes#755] opened 2015-07-24 12:18 UTC
I've set the crafting module to satellite pipe 4 and it works but after some time it does not show it anymore in the GUI (still sends items to satellite pipe 4 on crafting request)
Right now I have a total of 15 crafting modules with the satellite pipe function enabled and all are showing that its OFF (crafting still works).

<a href="http://imgur.com/3gC2tyR"><img src="http://i.imgur.com/3gC2tyR.jpg" title="source: imgur.com" /></a>

**Comment by bziemons** [comment] 2015-07-24 13:23
Actually a duplicate of #469. I will let both open, because this one has a screenshot.

**Closed as completed** 2016-02-25 19:31 UTC
Labels: Bug
