### ISSUE TITLE
OreDict ItemSink module is not working

### ISSUE THREAD

**Issue by NelkGames** [RS485/LogisticsPipes#1624] opened 2021-06-28 04:04 UTC
Hi, I'm playing and I noticed that the OreDict ItemSink module is not working, every time I put information in the module, when the HUD closes it is totally empty.
I tested the mod in version: 0.10.3.114 and 0.10.4.4

**Comment by bziemons** [comment] 2021-06-28 09:12
Duplicate of #1609

**Closed as completed by bziemons** 2021-06-28 09:12 UTC
