### ISSUE TITLE
Applied Energistics 2 Integration

### ISSUE THREAD

**Issue by Nex4rius** [RS485/LogisticsPipes#748] opened 2015-07-22 10:26 UTC
(The logistics pipe system can see the items inside the ME System but it cannot see / request crafting from the ME System.)

When a Basic Logistics Pipe is connected to a ME Interface it does not check if the ME System is full before items are being sent to the pipe. The items are just sent back and forth between this pipe and default itemsink / quicksort module.

logisticspipes-0.9.1.15
appliedenergistics2-rv2-stable-10

**Comment by ruifung** [comment] 2015-07-22 10:29
This is a duplicate of #53 . Over 2 years ago.

**Comment by ruifung** [comment] 2015-07-22 10:30
The crafting thing is a old old request. #53. (And I'm still waiting for it =P)

That being said, LP probably should check the interface's actual inventory for space when routing items to it. Sounds like it doesn't check that?

**Comment by hron84** [comment] 2015-07-22 10:54
And what about the opposite side? AE2 can use LP network?

**Comment by Nex4rius** [comment] 2015-07-22 10:57
@hron84 The opposite direction has to be done by ae2 not lp and they are "working on it".

**Comment by hron84** [comment] 2015-07-22 11:05
There's no way to provide a block for them? E.g. ExtraCells is a very external mod, not directly related to AE2 but can integrate with their storage and crafting system (okay, kind of, but... good for starting point). Same for Thaumic Energistics. If we can provide items in the system on this way, even if only the stored items (and not the craftable ones) that would be good. For example via DSU API?

**Comment by davboecki** [comment] 2015-07-22 11:37
Please move a discussion about AE2 crafting integration to the mentioned issue.

Basic Pipes NEVER check the connected inventory. Only Chassi pipes do that and they also do that on AE2 iirc.

And inventory access from AE2's side should be handled by them. It was in AE1 on their end and our API interfaces are nearly the same as they where then. We already have so many mod interactions that it is starting to get difficult to keep track of all of them.

**Closed as completed by davboecki** 2015-07-22 11:37 UTC
