### ISSUE TITLE
Chassi+provider module not working with multiple chests connected to it

### ISSUE THREAD

**Issue by ghost** [RS485/LogisticsPipes#1047] opened 2016-08-25 09:58 UTC
This is my setup
![image](https://cloud.githubusercontent.com/assets/18379029/17964765/05f1a118-6abb-11e6-8f45-75f5534c0342.png)
When I look into a request pipe I only see items from 1 chest, but if I change the chassi for a provider pipe it works. I'm using the chassi to also have an itemsink module which only routes items into 1 chest.

**Comment by 1n5aN1aC** [comment] 2016-08-25 17:34
Yes, this is the way chassis pipes work.

They choose one inventory to connect to, and you can change which one with a wrench or something.

It's actually really useful when working in tight spaces.

**Comment by hron84** [comment] 2016-08-26 08:26
Yeah, as @1n5aN1aC said this is how pipes were designed, There is no way to tell which provider module work with which chest, it can be done only in per-pipe basis. So if you wanna work with multiple chests, connect a pipe for each of them. I recommend you a mk2 pipe with a provider and a itemsink/polymorphic module. Protip: if you use polymorphic, don't forget to set the provider to leave 1 item per type.

**Comment by SonOfTheStars** [comment] 2016-08-26 09:48
Indeed, Chassis Pipes are **DESIGNED** to only be able to connect to one inventory. Its also indicated by the Orange Dots on the the Pipes, Structural Arms that face the currently connected Inventory.
Notice one Side of the Pipe has both a Red and an Orange mark on it. thats the currently selected Inventory.

Im sorry but theres no way you can access 4 Inventories With both In and Output in a single pipe. And thats by design.

**Comment by ghost** [comment] 2016-08-26 10:48
Ahh okay thank you all. Redesigned my system, using a provider and a basic for 2 double chests.

**Comment by hron84** [comment] 2016-08-26 12:59
@Bitterholz i think we could close this then.

**Comment by Sakata-MC** [comment] 2016-09-20 19:01
@tutkis While the devs certainly appreciate any bug reports, please, if they are resolved or not bugs, close the issue. Open issues that shouldn't be open make for a sad dev.

**Closed as completed** 2016-09-21 08:04 UTC
Labels: Invalid
