### ISSUE TITLE
Request Pipe not working with AE Interface

### ISSUE THREAD

**Issue by Timeslice42** [RS485/LogisticsPipes#896] opened 2016-01-11 18:42 UTC
Attaching a provider to an AE2 interface does correctly allow my LP network to see (and obtain) the items in my AE2 network. However putting a request pipe (mk1 or mk2) on an interface does not provide my LP items to AE2. I've tried attaching it to a different interface, and I tried removing all (one) providers from AE2 interfaces. AE2 still does not show me access to the LP items.

**Comment by hron84** [comment] 2016-01-13 09:30
Dupe of many others. Improving AE2 integration is in progress on #786 please take a look there. Please be patient, this is not a trivial integration, both on LP an AE side there is a lot of things that should be figured out in game logic before the integration could happen.

**Closed as completed** 2016-02-20 14:46 UTC
Labels: Duplicate
