### ISSUE TITLE
Suppliers need Better UI for Configuring Requested Ammounts

### ISSUE THREAD

**Issue by mikeloeven** [RS485/LogisticsPipes#852] opened 2015-11-15 22:40 UTC
Having serious issues configuring the supplier module for my fuel storage system due to the lack of a proper quantity selection. Currently you can only drag several stacks of items into the suppliers 3x3 grid however I have a situation where i need to keep a Deep Storage Unit Stocked with around 10K charcoal and it is simply impractical to configure this as there exists no easy way to enter large quantities into a supplier

**Comment by SonOfTheStars** [comment] 2015-11-16 17:53
Allready on the List for the Next LP Milestone. Actually this request has been arround for a LOOONG time.

**Comment by bziemons** [comment] 2015-11-21 13:15
Duplicate of #484.

**Closed as completed by bziemons** 2015-11-21 13:15 UTC
Labels: Duplicate
