### ISSUE TITLE
Crafting Recipes disappearing

### ISSUE THREAD

**Issue by NappingPanda** [RS485/LogisticsPipes#1514] opened 2020-08-07 03:29 UTC
Bug Report:
When input recipes into the crafting modules for logistic pipes, the inputs and outputs are disappearing from the recipe after exit. I expect this to be a mod issue unsure as I cannot see another bug report regarding this.

Expected Behavior/Suggestions:
Recipes should remain after exiting
Before Crafting Module
![Before Crafting Module](https://user-images.githubusercontent.com/47096154/89605882-018cbb80-d8b2-11ea-80d0-d76590dcc2fb.png)

After Crafting Module
![After Crafting Module](https://user-images.githubusercontent.com/47096154/89605891-03ef1580-d8b2-11ea-9166-00ca8ff6ea3f.png)

Is It Repeatable? Steps to Reproduce:
The items which are forgotten seem to be random.
Use pipe manager on pipe, click on crafting module.
Input recipe
exit module
Re-enter module - see some items have disappeared from recipe

**Comment by chrischtea** [comment] 2020-08-19 20:55
Can confirm.
Also cannot save recipe for GregTech Resistors (1 coal dust + 4 fine copper wire = **12** Resistors). The output gets cleared if the number is not 2^n (1,2,4,8,16,etc).
Edit: any number not 2^n will be ignored (input and output)
Using version 0.10.3.51 in FTB Immersion 2.0.7

**Comment by Heldenkrieger01** [comment] 2020-08-23 17:44
I confirm this too.
For us, the output slot only saves when it is one item.
Using FTB Interactions 2.0.7 with version 0.10.3.51 and Forge 14.23.5.2847

Edit: Here is a video
[Video of the bug in above mentioned version](https://imgur.com/a/wNj2cdY)

**Comment by janbue** [comment] 2020-08-23 17:56
Can confirm as well, but only saves when it is one item. 

When sharing world via Open to LAN it worked on the host but not on the client.
Using FTB Interactions 2.0.7 with version 0.10.3.51 and Forge 14.23.5.2847

**Comment by ArmaWizard** [comment] 2020-08-24 15:19
I notice this also happening. When it happens, break the pipe and replace it. Because if it happens one time then on server reboot it will be even more broken. Replacing the pipe permanently fixes it.

**Comment by janbue** [comment] 2020-08-24 15:22
It's not only happening if creating recipe in pipe also when creating directly from inventory

**Comment by Heldenkrieger01** [comment] 2020-08-24 15:25
> I notice this also happening. When it happens, break the pipe and replace it. Because if it happens one time then on server reboot it will be even more broken. Replacing the pipe permanently fixes it.

As you see in my video, this issue is completely unrelated to any pipe. This happened to a brand new crafting card.

**Comment by chrischtea** [comment] 2020-08-24 19:09
Just updated to pack version 2.0.9 / LP version 0.10.3.62 but the forgetting problem persists.
I could narrow it down to multiplayer. It works in single player for me.

**Comment by Heldenkrieger01** [comment] 2020-08-28 18:51
Update: This also applies to the inputs as well!

**Comment by CyrelV** [comment] 2020-09-01 20:06
Can confirm this issue persists in logisticspipes-0.10.3.62 as part of the FTB Interactions (2.0.9) modpack. It seems to happen whenever I attempt to increase the quantity of an item. If I leave the quantity untouched or use that quantity of item to directly add that quantity to the interface, it is fine. Any alteration to that quantity with the mouse wheel causes the recipe to disappear upon closing the interface.

Steps to reproduce:

- Obtain a Crafting Module
- Right click to open up the GUI
- Drag ANYTHING from JEI into one of the slots
- Mouse wheel scroll upwards to increase the quantity to anything
- Close the GUI (escape, 'e', doesn't matter)
- Right-click to re-open the GUI
- Observe the slot you attempted to modify is now empty

**Comment by CyrelV** [comment] 2020-09-20 12:32
Possibly useful addendum to my example above, with an item in the crafting manager GUI with a quantity set (say 8) with at least that much in my inventory as well:
- Mouse-wheel down cuts the quantity in the GUI in half, reduces it by 1[if still than 2] (to 3), and then picks up the halved quantity from my inventory

**Comment by CameronBarnes** [comment] 2020-10-09 14:55
Can confirm I have the issue as well. FTB Interactions 2.0.9 logisticspipes-0.10.3.62. Multiples of 2 are deleted while multiples of 4 for the same item in other recipies are not, 2 fine red alloy wire gets deleted, 4 fine red alloy wire does not. 4 redstone dust however does get removed, so it doesnt appear to be strictly number specific. I can also confirm that it's not an issue in single player.

**Comment by insanetwo** [comment] 2021-03-20 15:47
Can confirm the bug still occurs.  However, for me it only appears while on a multiplayer server.  When switching to a single player world, the crafting module functions as expected and allows stacks of two or higher in the output.

Also, as discovered elsewhere, there is a workaround where you use the exact quantity of the item to set the amount.  If you do not use the mouse wheel to adjust the stack size, then the recipe will stay.

**Closed as completed** 2021-04-20 16:57 UTC
Labels: Bug, Accepted
