### ISSUE TITLE
Logistics Crafting Table rendering error reported by CCL

### ISSUE THREAD

**Issue by xJon** [RS485/LogisticsPipes#1661] opened 2022-09-02 18:35 UTC
First reported over https://github.com/xJon/Tekkit-2/issues/36, seen in the game log over: https://mclo.gs/Hw824jj#L10303
Not sure whether a mod incompatibility causes this or a problem with Logistics Pipes

**Comment by bziemons** [comment] 2022-09-02 19:51
Seems like a duplicate of https://github.com/RS485/LogisticsPipes/issues/1534

**Comment by bziemons** [comment] 2022-09-02 19:54
However, I see relocation is involved in the stack trace:

```
at mrtjp.projectred.relocation.MovingBlockRenderDispatcher.renderBlock(renders.scala:277) [MovingBlockRenderDispatcher.class:?]
```

not sure, if that is an issue here.

**Comment by xJon** [comment] 2022-09-02 20:02
@bziemons The player said they didn't use relocation in their world, so it's probably a duplicate? feel free to close in that case!

**Comment by bziemons** [comment] 2022-09-02 20:03
Nah, seems fine. I looked at the project red code and it doesn't do anything odd to the parameters

**Comment by MCDemon117** [comment] 2022-09-03 07:09
It was my report xJon mentioned, as it said in the report it started appearing after I got back from the Moon the first time, it wasn't much of a problem but now it is, it just kept coming in the chat per minute.

**Comment by xJon** [comment] 2022-09-03 10:36
@MCDemon117 You can disable the chat warnings in the `codechickenlib.cfg` config.
Edit: now disabled by default in Tekkit 2.

**Closed as completed** 2022-09-05 01:36 UTC
