### ISSUE TITLE
Add a new crafting module/crafting pipe tier that handles fluid as a recipe output

### ISSUE THREAD

**Issue by mahldcat** [RS485/LogisticsPipes#1017] opened 2016-06-08 17:56 UTC
This is essentially an inverse to the current state of LP which can use a fluid satellite pipe to input a fluid.  I would like the ability to autocraft fluids using a similar process, where it may not make sense to continuously produce a given fluid:

**Use Case #1:**
Automating Thermal Dynamics Magma Crucible:  
     Input:  1 block of redstone
     Output: (XXXX mb of destabilized redstone) (to satellite pipe #42)

**Use Case #2:**
Automating Immersive Engineering's Industrial Squeezer to produce Seed Oil:
     Input : 1 pumpkin seed
     Output:  (XXXX mb of seed oil) (to satellite pipe #43)

**Use Case #3:**
Automated TiCon's smeltery to produce Signalum Alloy:
     Input:  1 ingot of silver, 3 ingots of copper, 1000 mb destabilized redstone (satellite pipe #44)
     Output:  576 mb of Signalum (to satellite pipe #45)

**Comment by AEnterprise** [comment] 2016-06-08 19:28
these can already be automated, if the magma crucible fluid is used in another machine just have it auto-eject to that and feed the magma crucible with that

for just creating fluids use an infinite active supplier on the machine that makes it and put a liquid provider pipe on it

for the smeltery just use a fluid supplier and/or the above techniques to keep 1000mb of destablilized redstone at all times in the smeltery and have the use filtered liquid extraction to put said signalum in a casting table/basin to make the ingots the crafting pipe can extract

**Comment by SonOfTheStars** [comment] 2016-06-09 11:47
If you want, you can technically keep Tanks aside and Task your Crafting to Pull Fluid from the Tank, while also inserting more material into the MagmaCrucible/Smeltery wich then gets pulled back into the tank.

**Comment by bziemons** [comment] 2017-05-20 11:36
I agree, this would be cool.

**Comment by bziemons** [comment] 2020-06-10 18:16
Duplicate of #635

**Closed as completed by bziemons** 2020-06-10 18:16 UTC
Labels: Duplicate, Enhancement
