### ISSUE TITLE
Problems with craftings that can use Ore Dictionary.

### ISSUE THREAD

**Issue by NelkGames** [RS485/LogisticsPipes#1393] opened 2019-11-13 20:03 UTC
Hi, I'm playing a modpack I created and I'm having some problems with craftings that can use Ore Dictionary. I made several attempts and nothing, even using the logistic crafting pipe module or the fuzzy crafting table, the game doesn't recognize the recipe.
I want to know if there are any solutions or I am using these items incorrectly.
Thanks.

**Comment by Sakata-MC** [comment] 2020-01-13 20:17
You need fuzzy crafting table *AND* fuzzy module

**Comment by NelkGames** [comment] 2020-01-13 20:24
> You need fuzzy crafting table _AND_ fuzzy module

I know that, but still the crafting doesn't work. I haven't been playing in a while and saw that there were updates, I'll check to see if the problem continues.

**Comment by bziemons** [comment] 2021-04-18 13:41
Probably a duplicate of #979

**Closed as completed by bziemons** 2021-04-18 13:41 UTC
Labels: Bug, Duplicate
