### ISSUE TITLE
10.3.36: Crash when hitting "+" for recipe ChassisMK2 in lpRequestTable

### ISSUE THREAD

**Issue by Ioandar** [RS485/LogisticsPipes#1481] opened 2020-06-15 10:52 UTC
only thing I changed is updating LP. Going back to former LP version and all is fine again
anyone else has this or is it just me (local issue)? 

Forge: 14.23.5.2854

Works fine with 10.3.29
Crashes with 10.3.36

https://pastebin.com/8Vp6Ebj8

<img src="https://i.ibb.co/gyCCwTX/2020-06-15-12-26-36-crash-MK2.png" alt="2020-06-15-12-26-36-crash-MK2" border="0">

**Comment by bziemons** [comment] 2020-06-15 11:15
Duplicate of #1480

**Closed as completed by bziemons** 2020-06-15 11:15 UTC
Labels: Duplicate
