### ISSUE TITLE
LP and FORESTRY

### ISSUE THREAD

**Issue by O13SC3N3** [RS485/LogisticsPipes#906] opened 2016-02-02 03:50 UTC
LP: 0.9.3.70
Forestry: 4.2.6.54
Forge: 1566

following error pops up in the console on startup, haven't really dived into LP/Forestry to find if a more underlying issue is involved. Posted at Forestry as well.

http://pastebin.com/aLGfDx2G

more

http://pastebin.com/QrSRz2jx

**Comment by O13SC3N3** [comment] 2016-02-02 05:42
[https://github.com/RS485/LogisticsPipes/issues/906](url)

**Comment by hron84** [comment] 2016-02-02 12:36
The link is wrong, ForestryMC/ForestryMC#1055

**Comment by joral** [comment] 2016-02-03 13:33
Updating the path to that class works.  The question I have is this: should we try to support both, or just the most recent?  It wouldn't be too difficult to check which package holds the class before we try to instantiate it.

**Comment by O13SC3N3** [comment] 2016-02-03 20:59
well what I see is people who like binnies mods is staying with forestry 3.XXX but most people are making the switch to forestry 4.xx and dropping that mod to use the latest versions of other mods like immersive engineering etc.. that just an outside view

**Comment by bookerthegeek** [comment] 2016-02-03 21:25
I must agree, with bonnie not updating, he had to be dropped. Can't have another  RP situation.

**Comment by hron84** [comment] 2016-02-05 12:02
Is there any way to someone pick up binnie's mod and continue the work? We will lose a lot of fun if ExtraBees will be dropped.

**Comment by O13SC3N3** [comment] 2016-02-05 14:22
Many people would but it was and is Bonnie's license on the mod "All Rights Reserved" which nobody can update to the new API and distribute. Now this doesn't mean you can't do it yourself for personal use and don't give it out. Either way its against the license.

**Comment by O13SC3N3** [comment] 2016-02-06 21:55
Is there a fix foreseeable in the future?

**Comment by joral** [comment] 2016-02-07 01:10
Yes.  I will submit the pull request for dev tonight.  I also have the change made against bc7 stable, since I'm running a server with RR3.

**Comment by O13SC3N3** [comment] 2016-02-07 04:08
Cool thanks for the update!

**Comment by joral** [comment] 2016-02-07 17:17
Submitted for dev branch. Not sure where we go from here.

**Comment by O13SC3N3** [comment] 2016-02-07 23:35
> Submitted for dev branch. Not sure where we go from here.

Im not sure what you mean by where we go from here?

**Comment by davboecki** [comment] 2016-02-09 13:44
PR merged.

**Comment by O13SC3N3** [comment] 2016-02-09 18:06
Build 71 and 72 still receive the following http://pastebin.com/raw/yT1FmYz3

**Comment by loordgek** [comment] 2016-02-10 09:17
found it https://github.com/joral/LogisticsPipes/blob/aba1b1a34fad026e13bb4e3ce36747a168ae536d/common/logisticspipes/proxy/forestry/ForestryProgressProvider.java
@joral can you fix this to ??

**Comment by hron84** [comment] 2016-02-10 17:19
The problem is the class now named as `forestry.core.tiles.TilePowered`, the `gadgets` package get renamed at [1e89bab](https://github.com/ForestryMC/ForestryMC/commit/1e89bab5567a014f36ab41c4434ea717b88d6b82)

**Comment by joral** [comment] 2016-02-10 18:00
I should be able to tonight.

**Comment by joral** [comment] 2016-02-12 20:22
Ok.  Need to get a newer API package for Forestry first.  The move from Forestry 3 to Forestry 4 is when it looks like the paths were updated.  Having trouble connecting to the build server for Forestry to get the new API.  Will keep trying.

**Comment by O13SC3N3** [comment] 2016-02-15 04:09
Any luck m8?

**Closed as completed** 2016-02-15 09:57 UTC
