### ISSUE TITLE
Apiary Refiller doesnt work anymore since Forestry API change

### ISSUE THREAD

**Issue by thatsIch** [RS485/LogisticsPipes#88] opened 2013-06-06 13:04 UTC
- LogisticPipes 0.7.3.480
- Forestry 2.2.6.3

It can eject all content of the apiaries, but not re-insert them though they are pure breds.

**Comment by davboecki** [comment] 2013-06-10 00:12
should be fixed inside new dev builds. Please retest.

**Comment by thatsIch** [comment] 2013-06-10 07:56
ok I am on it

**Comment by thatsIch** [comment] 2013-06-10 11:18
Tested with 
- Forge 7.8.0.732
- LogisticPipes 0.7.3.503
- Forestry 2.2.6.3
- ExtraBees 1.6.13

still no Refilling

**Comment by davboecki** [comment] 2013-06-10 20:01
Can you make some screenshots of your setup including the apiary GUI.

**Comment by theron61** [comment] 2013-06-11 01:26
I'm having a similar issue.  It appears the issue is larger than the Apiary Refiller as there do not appear to be a valid recipe for the Bee related pipes or items.  I am running the same version as the parent.

**Comment by ClaudiaJ** [comment] 2013-06-11 08:40
I have one MK2 Chassis on the bottom of 7 alvearies, all with Apiary Refiller modules, a setup I've used in 1.4.7 just fine. these are all connected to a chest with an item sink set as default destination. When work is finished, drones and princesses are all deposited into this chest along with their respective products, rather than recycling through their alvearies as anticipated.
- Logistics Pipes 0.7.3.dev.503
- Forge 7.8.0.729
- Forestry 2.2.6.3
- ExtraBees 1.6-pre13

Screenshots uploaded [here](http://imgur.com/d3JUmXH,KPvwgtA,3ISONps)

**Comment by thatsIch** [comment] 2013-06-11 18:16
ScreenShots of Setup: http://imgur.com/a/uN7JZ
In the last picture all bees where extracted. Since I used this setup in 1.4.7 and in 1.5.2 already too (so it worked once with Forestry 2.2.4.x)

€: http://imgur.com/a/9yLFk imgur derped

**Comment by ClaudiaJ** [comment] 2013-06-12 07:37
With the same setup in my screenshots using build 511, the queen is automagically reinserted only after I manually pull out the drones.

**Comment by davboecki** [comment] 2013-06-12 10:00
Is there a place for the drones to go. An Bee Analyser Pipe/module?

**Comment by ClaudiaJ** [comment] 2013-06-12 21:57
I've added a drone terminus module to the network, everything works fine now. I misunderstood how the refiller module was supposed to function.

**Closed as completed** 2013-06-13 09:23 UTC
Labels: Bug
