### ISSUE TITLE
Crafting pipe/modules sometimes don't notice when crafting is complete

### ISSUE THREAD

**Issue by StarkRG** [RS485/LogisticsPipes#1354] opened 2019-08-02 17:40 UTC
This happens when the crafting pipe or module isn't the entity to pull the item out of the machine, such as if there's also an extractor module in the chassis or if the machine itself pushes the item into the pipe (such as a GTCE blast furnace). This results in the crafting request remaining in the queue indefinitely. 

What should happen is that the crafting pipe or module should notice when a requested item enters the pipe from the machine (rather than another pipe) instead of needing to be the one to pull it out.

**Comment by Bernasss12** [comment] 2019-08-02 17:54
I believe this is the intended behaviour, the solution is to not have an extractor module in the same chassis pipe as a crafting module.

**Comment by StarkRG** [comment] 2019-08-02 19:43
And what's the solution for machines that push into the pipe?

**Comment by ZenDarva** [comment] 2019-08-02 20:43
Attach the crafting pipe to a buffer chest, have the machine pull from, and push to the buffer chest.

**Comment by StarkRG** [comment] 2019-08-02 20:44
If that's really the intended behavior, that seems overly clunky.

**Comment by ZenDarva** [comment] 2019-08-02 21:12
Well, the machine is behaving incorrectly if you can't disable autopush.  Why is that Logistic Pipes fault?

**Comment by Bernasss12** [comment] 2019-08-02 21:19
Afaik there is a plan to improve this situation but I don't really know any kind of details

**Comment by bziemons** [comment] 2019-08-03 09:01
There always was this problem with the BC assembly table and it is very easy to workaround, but PRs are welcome.

Duplicate of #255

**Closed as completed by bziemons** 2019-08-03 09:01 UTC
Labels: Duplicate
