### ISSUE TITLE
IllegalArgumentException in AEInterfaceInventoryHandler

### ISSUE THREAD

**Issue by Musician101** [RS485/LogisticsPipes#516] opened 2014-11-27 01:10 UTC
Attached a Supplier Pipe to an AE2 ME Interface (the full block type) and it crashed my client. Can't access the world without using MCEdit to go in and remove the pipe.

Crash Log: http://pastebin.com/6vqvYRw6

**Comment by ruifung** [comment] 2014-11-27 04:16
Outdated build. build 82 contains a fix for this, duplicate of #507 .

**Closed as completed** 2014-11-27 04:54 UTC
